AWSTemplateFormatVersion: '2010-09-09'
Description: DNS CloudFront

Parameters:
  EnvironmentName:
    Type: String

  DomainName:
    Type: String

  HostedZoneName:
    Type: String
    Default: "✅Colocar aqui seu DNS, deixar o ponto no final".

Resources:
  DNSA:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Ref HostedZoneName
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName:
          Fn::ImportValue:
            Fn::Sub: "${EnvironmentName}-cf-domain"
        HostedZoneId: "✅Colocar aqui seu ID da sua distribuição do CloudFront, deixar o ponto no final"

  DNSAAAA:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Ref HostedZoneName
      Name: !Ref DomainName
      Type: AAAA
      AliasTarget:
        DNSName:
          Fn::ImportValue:
            Fn::Sub: "${EnvironmentName}-cf-domain"
        HostedZoneId: "✅Colocar aqui seu ID da sua distribuição do CloudFront, deixar o ponto no final"
